// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_DFPfFdelygKscFfPoWrXOQpCO-hg6kQ',
    appId: '1:388871201510:web:365b8b0ee714edc75d9127',
    messagingSenderId: '388871201510',
    projectId: 'tubes-kripto-ab756',
    authDomain: 'tubes-kripto-ab756.firebaseapp.com',
    storageBucket: 'tubes-kripto-ab756.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUE4qvOIO9B4Wmj_YLn-k-xu7h9r9jQgs',
    appId: '1:388871201510:android:03e692d2ff7851025d9127',
    messagingSenderId: '388871201510',
    projectId: 'tubes-kripto-ab756',
    storageBucket: 'tubes-kripto-ab756.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDREyHWfU6AncqcSDSrxo87PCJRTAKVSwM',
    appId: '1:388871201510:ios:eec52c27e85ad6d15d9127',
    messagingSenderId: '388871201510',
    projectId: 'tubes-kripto-ab756',
    storageBucket: 'tubes-kripto-ab756.firebasestorage.app',
    iosBundleId: 'com.example.tubesKripto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDREyHWfU6AncqcSDSrxo87PCJRTAKVSwM',
    appId: '1:388871201510:ios:eec52c27e85ad6d15d9127',
    messagingSenderId: '388871201510',
    projectId: 'tubes-kripto-ab756',
    storageBucket: 'tubes-kripto-ab756.firebasestorage.app',
    iosBundleId: 'com.example.tubesKripto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_DFPfFdelygKscFfPoWrXOQpCO-hg6kQ',
    appId: '1:388871201510:web:868e01adfcb1c2625d9127',
    messagingSenderId: '388871201510',
    projectId: 'tubes-kripto-ab756',
    authDomain: 'tubes-kripto-ab756.firebaseapp.com',
    storageBucket: 'tubes-kripto-ab756.firebasestorage.app',
  );
}
